[build]
  # CRITICAL FIX: Tell Netlify the base directory is the repo root.
  # We set the publish directory to the functions folder, which is where Netlify
  # can find the files, even though it's API-only.
  publish = "netlify/functions"
  command = "" 

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://geordiekingsbeer.github.io"
    Access-Control-Allow-Methods = "POST, GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Max-Age = "86400"
