[build]
  command = "" 
  publish = "netlify/functions"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# THIS SECTION FORCES HEADERS AT THE CDN LEVEL FOR ALL FUNCTION CALLS
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://geordiekingsbeer.github.io"
    Access-Control-Allow-Methods = "POST, GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Max-Age = "86400"
